version: '3'

services:
  django_staff:
    build: ./staff_site
    container_name: django_staff
    ports:
      - '10.0.0.2:8008:8008'
    env_file:
      - ./staff_site/.env
    command: gunicorn staff_site.wsgi:application --bind 0.0.0.0:8008
    volumes:
      - ./staff_site/:/usr/src/app-staff/
  celery:
    container_name: cl01_staff
    build: ./staff_site
    command: celery -A staff_site worker -l info --purge
    env_file:
      - ./staff_site/.env
    volumes:
      - ./staff_site/:/usr/src/app-staff/
  celery-beat:
    container_name: cl01_beat_staff
    build: ./staff_site
    command: celery -A staff_site beat -l info
    env_file:
      - ./staff_site/.env
    volumes:
      - ./staff_site/:/usr/src/app-staff/