version: '3'

services:
  django_staff:
    build: ./staff_site
    container_name: django_staff
    ports:
      - '10.0.0.2:8008:8008'
    env_file:
      - ./staff_site/.env
    command: gunicorn staff_site.wsgi:application --bind 0.0.0.0:8008
    volumes:
      - ./staff_site/:/usr/src/app-staff/
  #cronjobs:
   # build: ./cronjob
   # container_name: cronjobs
   # volumes:
    #  - ./staff_site/:/usr/src/app-staff/

